// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: scanner.jflex


@SuppressWarnings("fallthrough")
class LexTest {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1d00\1\u1e00"+
    "\1\u1f00\1\u2000\2\u2100\1\u2200\7\u2100\1\u2300\1\u2400\1\u2500"+
    "\1\u2100\1\u2600\1\u2700\2\u2100\31\u1100\1\u2800\121\u1100\1\u2900"+
    "\4\u1100\1\u2a00\1\u1100\1\u2b00\1\u2c00\1\u2d00\1\u2e00\1\u2f00"+
    "\1\u3000\53\u1100\1\u3100\10\u3200\31\u2100\1\u1100\1\u3300\1\u3400"+
    "\1\u1100\1\u3500\1\u3600\1\u3700\1\u3800\1\u2100\1\u3900\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u1100\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u2100\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u2100"+
    "\1\u5000\1\u5100\1\u5200\1\u2100\3\u1100\1\u5300\1\u5400\1\u5500"+
    "\12\u2100\4\u1100\1\u5600\17\u2100\2\u1100\1\u5700\41\u2100\2\u1100"+
    "\1\u5800\1\u5900\2\u2100\1\u5a00\1\u5b00\27\u1100\1\u5c00\2\u1100"+
    "\1\u5d00\45\u2100\1\u1100\1\u5e00\1\u5f00\11\u2100\1\u6000\27\u2100"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\11\u2100\1\u6500\1\u6600\5\u2100"+
    "\1\u6700\1\u6800\4\u2100\1\u6900\2\u2100\1\u6a00\16\u2100\246\u1100"+
    "\1\u6b00\20\u1100\1\u6c00\1\u6d00\25\u1100\1\u6e00\34\u1100\1\u6f00"+
    "\14\u2100\2\u1100\1\u7000\u0e05\u2100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\12\23\1\24"+
    "\1\25\1\26\1\27\1\30\2\0\32\31\1\32\1\33"+
    "\1\34\1\0\1\35\1\0\1\36\2\37\1\40\1\41"+
    "\1\42\2\37\1\43\2\37\1\44\1\37\1\45\1\37"+
    "\1\46\1\37\1\47\1\50\1\51\1\52\1\37\1\53"+
    "\3\37\1\54\1\0\1\55\7\0\1\3\44\0\1\37"+
    "\12\0\1\37\4\0\1\37\5\0\27\31\1\0\7\31"+
    "\30\37\1\0\10\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\2\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\2\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\2\31\1\37\1\31\1\37\1\31\3\37\2\31"+
    "\1\37\1\31\1\37\2\31\1\37\3\31\2\37\4\31"+
    "\1\37\2\31\1\37\3\31\3\37\2\31\1\37\2\31"+
    "\1\37\1\31\1\37\1\31\1\37\2\31\1\37\1\31"+
    "\2\37\1\31\1\37\2\31\1\37\3\31\1\37\1\31"+
    "\1\37\2\31\2\37\1\35\1\31\3\37\4\35\1\31"+
    "\1\35\1\37\1\31\1\35\1\37\1\31\1\35\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\2\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\2\37\1\31\1\35\1\37\1\31\1\37\3\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\7\37\2\31\1\37\2\31\2\37\1\31"+
    "\1\37\4\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\105\37\1\35\44\37\7\35\2\37\4\0"+
    "\14\35\16\0\5\37\7\0\1\35\1\0\1\35\126\0"+
    "\1\56\52\0\1\31\1\37\1\31\1\37\1\35\1\0"+
    "\1\31\1\37\2\0\4\37\1\0\1\31\6\0\1\31"+
    "\1\0\3\31\1\0\1\31\1\0\2\31\1\37\21\31"+
    "\1\0\11\31\43\37\1\31\2\37\3\31\3\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\5\37\1\31"+
    "\1\37\1\0\1\31\1\37\2\31\2\37\63\31\60\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\10\0\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\2\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\2\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\0"+
    "\46\31\2\0\1\35\6\0\51\37\107\0\33\35\4\0"+
    "\4\35\55\0\53\35\25\0\12\57\4\0\2\35\1\0"+
    "\143\35\1\0\1\35\17\0\2\35\7\0\2\35\12\57"+
    "\3\35\2\0\1\35\20\0\1\35\1\0\36\35\35\0"+
    "\131\35\13\0\1\35\16\0\12\57\41\35\11\0\2\35"+
    "\4\0\1\35\5\0\26\35\4\0\1\35\11\0\1\35"+
    "\3\0\1\35\27\0\31\35\7\0\13\35\65\0\25\35"+
    "\1\0\10\35\106\0\66\35\3\0\1\35\22\0\1\35"+
    "\7\0\12\35\4\0\12\57\1\0\20\35\4\0\10\35"+
    "\2\0\2\35\2\0\26\35\1\0\7\35\1\0\1\35"+
    "\3\0\4\35\3\0\1\35\20\0\1\35\15\0\2\35"+
    "\1\0\3\35\4\0\12\57\2\35\12\0\1\35\10\0"+
    "\6\35\4\0\2\35\2\0\26\35\1\0\7\35\1\0"+
    "\2\35\1\0\2\35\1\0\2\35\37\0\4\35\1\0"+
    "\1\35\7\0\12\57\2\0\3\35\20\0\11\35\1\0"+
    "\3\35\1\0\26\35\1\0\7\35\1\0\2\35\1\0"+
    "\5\35\3\0\1\35\22\0\1\35\17\0\2\35\4\0"+
    "\12\57\11\0\1\35\13\0\10\35\2\0\2\35\2\0"+
    "\26\35\1\0\7\35\1\0\2\35\1\0\5\35\3\0"+
    "\1\35\36\0\2\35\1\0\3\35\4\0\12\57\1\0"+
    "\1\35\21\0\1\35\1\0\6\35\3\0\3\35\1\0"+
    "\4\35\3\0\2\35\1\0\1\35\1\0\2\35\3\0"+
    "\2\35\3\0\3\35\3\0\14\35\26\0\1\35\25\0"+
    "\12\57\25\0\10\35\1\0\3\35\1\0\27\35\1\0"+
    "\20\35\3\0\1\35\32\0\3\35\5\0\2\35\4\0"+
    "\12\57\20\0\1\35\4\0\10\35\1\0\3\35\1\0"+
    "\27\35\1\0\12\35\1\0\5\35\3\0\1\35\40\0"+
    "\1\35\1\0\2\35\4\0\12\57\1\0\2\35\22\0"+
    "\10\35\1\0\3\35\1\0\51\35\2\0\1\35\20\0"+
    "\1\35\5\0\3\35\10\0\3\35\4\0\12\57\12\0"+
    "\6\35\5\0\22\35\3\0\30\35\1\0\11\35\1\0"+
    "\1\35\2\0\7\35\37\0\12\57\21\0\60\35\1\0"+
    "\2\35\14\0\7\35\11\0\12\57\47\0\2\35\1\0"+
    "\1\35\1\0\5\35\1\0\30\35\1\0\1\35\1\0"+
    "\12\35\1\0\2\35\11\0\1\35\2\0\5\35\1\0"+
    "\1\35\11\0\12\57\2\0\4\35\40\0\1\35\37\0"+
    "\12\57\26\0\10\35\1\0\44\35\33\0\5\35\163\0"+
    "\53\35\24\0\1\35\12\57\6\0\6\35\4\0\4\35"+
    "\3\0\1\35\3\0\2\35\7\0\3\35\4\0\15\35"+
    "\14\0\1\35\1\0\12\57\6\0\46\31\1\0\1\31"+
    "\5\0\1\31\2\0\53\37\1\0\1\35\3\37\u0149\35"+
    "\1\0\4\35\2\0\7\35\1\0\1\35\1\0\4\35"+
    "\2\0\51\35\1\0\4\35\2\0\41\35\1\0\4\35"+
    "\2\0\7\35\1\0\1\35\1\0\4\35\2\0\17\35"+
    "\1\0\71\35\1\0\4\35\2\0\103\35\45\0\20\35"+
    "\20\0\126\31\2\0\6\37\3\0\u016c\35\2\0\21\35"+
    "\1\0\32\35\5\0\113\35\6\0\10\35\7\0\15\35"+
    "\1\0\4\35\16\0\22\35\16\0\22\35\16\0\15\35"+
    "\1\0\3\35\17\0\64\35\43\0\1\35\4\0\1\35"+
    "\3\0\12\57\46\0\12\57\6\0\131\35\7\0\5\35"+
    "\2\0\42\35\1\0\1\35\5\0\106\35\12\0\37\35"+
    "\47\0\12\57\36\35\2\0\5\35\13\0\54\35\4\0"+
    "\32\35\6\0\12\57\46\0\27\35\11\0\65\35\53\0"+
    "\12\57\6\0\12\57\15\0\1\35\135\0\57\35\21\0"+
    "\7\35\4\0\12\57\51\0\36\35\15\0\2\35\12\57"+
    "\54\35\32\0\44\35\34\0\12\57\3\0\3\35\12\57"+
    "\44\35\2\0\11\37\7\0\53\31\2\0\3\31\51\0"+
    "\4\35\1\0\6\35\1\0\2\35\3\0\1\35\5\0"+
    "\300\37\100\0\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\11\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\11\37\10\31\6\37\2\0\6\31\2\0\10\37"+
    "\10\31\10\37\10\31\6\37\2\0\6\31\2\0\10\37"+
    "\1\0\1\31\1\0\1\31\1\0\1\31\1\0\1\31"+
    "\10\37\10\31\16\37\2\0\10\37\10\35\10\37\10\35"+
    "\10\37\10\35\5\37\1\0\2\37\4\31\1\35\1\0"+
    "\1\37\3\0\3\37\1\0\2\37\4\31\1\35\3\0"+
    "\4\37\2\0\2\37\4\31\4\0\10\37\5\31\5\0"+
    "\3\37\1\0\2\37\4\31\1\35\53\0\2\3\107\0"+
    "\1\37\15\0\1\37\20\0\15\37\145\0\1\31\4\0"+
    "\1\31\2\0\1\37\3\31\2\37\3\31\1\37\1\0"+
    "\1\31\3\0\5\31\6\0\1\31\1\0\1\31\1\0"+
    "\1\31\1\0\4\31\1\0\1\37\4\31\1\37\4\35"+
    "\1\37\2\0\2\37\2\31\5\0\1\31\4\37\4\0"+
    "\1\37\21\0\20\60\20\56\3\0\1\31\1\37\u0231\0"+
    "\32\60\32\56\26\0\57\31\1\0\57\37\1\0\1\31"+
    "\1\37\3\31\2\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\4\31\1\37\1\31\2\37\1\31\10\37\3\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\2\37\6\0\1\31\1\37\1\31\1\37"+
    "\3\0\1\31\1\37\14\0\46\37\1\0\1\37\5\0"+
    "\1\37\2\0\70\35\7\0\1\35\20\0\27\35\11\0"+
    "\7\35\1\0\7\35\1\0\7\35\1\0\7\35\1\0"+
    "\7\35\1\0\7\35\1\0\7\35\1\0\7\35\120\0"+
    "\1\35\325\0\2\35\52\0\5\35\5\0\2\35\4\0"+
    "\126\35\6\0\3\35\1\0\132\35\1\0\4\35\5\0"+
    "\53\35\1\0\136\35\21\0\33\35\65\0\306\35\112\0"+
    "\360\35\20\0\215\35\103\0\56\35\2\0\15\35\3\0"+
    "\20\35\12\57\2\35\24\0\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\35\20\0\1\35\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\3\37\2\0\106\35\61\0\11\35\2\0\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\3\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\31\12\37\1\31\1\37\1\31\1\37\2\31\1\37"+
    "\1\31\1\37\1\31\1\37\1\31\1\37\1\31\1\37"+
    "\1\35\2\0\1\31\1\37\1\31\1\37\1\35\1\31"+
    "\1\37\1\31\3\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\1\31\1\37\5\31"+
    "\1\37\5\31\1\37\1\31\1\37\1\31\1\37\1\31"+
    "\1\37\1\31\1\37\1\31\1\37\2\0\1\31\1\37"+
    "\3\31\60\0\1\35\3\37\7\35\1\0\3\35\1\0"+
    "\4\35\1\0\27\35\35\0\64\35\16\0\62\35\34\0"+
    "\12\57\30\0\6\35\3\0\1\35\1\0\2\35\1\0"+
    "\12\57\34\35\12\0\27\35\31\0\35\35\7\0\57\35"+
    "\34\0\1\35\12\57\6\0\5\35\1\0\12\35\12\57"+
    "\5\35\1\0\51\35\27\0\3\35\1\0\10\35\4\0"+
    "\12\57\6\0\27\35\3\0\1\35\3\0\62\35\1\0"+
    "\1\35\3\0\2\35\2\0\5\35\2\0\1\35\1\0"+
    "\1\35\30\0\3\35\2\0\13\35\7\0\3\35\14\0"+
    "\6\35\2\0\6\35\2\0\6\35\11\0\7\35\1\0"+
    "\7\35\1\0\53\37\1\0\14\37\10\0\120\37\43\35"+
    "\15\0\12\57\6\0\244\35\14\0\27\35\4\0\61\35"+
    "\4\0\u0100\3\156\35\2\0\152\35\46\0\7\37\14\0"+
    "\5\37\5\0\1\35\1\0\12\35\1\0\15\35\1\0"+
    "\5\35\1\0\1\35\1\0\2\35\1\0\2\35\1\0"+
    "\154\35\41\0\153\35\22\0\100\35\2\0\66\35\50\0"+
    "\14\35\164\0\5\35\1\0\207\35\23\0\12\57\7\0"+
    "\32\31\6\0\32\37\13\0\131\35\3\0\6\35\2\0"+
    "\6\35\2\0\6\35\2\0\3\35\43\0\14\35\1\0"+
    "\32\35\1\0\23\35\1\0\2\35\1\0\17\35\2\0"+
    "\16\35\42\0\173\35\205\0\35\35\3\0\61\35\57\0"+
    "\40\35\15\0\24\35\1\0\10\35\6\0\46\35\12\0"+
    "\36\35\2\0\44\35\4\0\10\35\60\0\50\31\50\37"+
    "\116\35\2\0\12\57\6\0\44\31\4\0\44\37\4\0"+
    "\50\35\10\0\64\35\234\0\67\35\11\0\26\35\12\0"+
    "\10\35\230\0\6\35\2\0\1\35\1\0\54\35\1\0"+
    "\2\35\3\0\1\35\2\0\27\35\12\0\27\35\11\0"+
    "\37\35\101\0\23\35\1\0\2\35\12\0\26\35\12\0"+
    "\32\35\106\0\70\35\6\0\2\35\100\0\1\35\17\0"+
    "\4\35\1\0\3\35\1\0\35\35\52\0\35\35\3\0"+
    "\35\35\43\0\10\35\1\0\34\35\33\0\66\35\12\0"+
    "\26\35\12\0\23\35\15\0\22\35\156\0\111\35\67\0"+
    "\63\31\15\0\63\37\15\0\44\35\14\0\12\57\306\0"+
    "\35\35\12\0\1\35\10\0\26\35\232\0\27\35\14\0"+
    "\65\35\56\0\12\57\23\0\55\35\40\0\31\35\7\0"+
    "\12\57\11\0\44\35\17\0\12\57\4\0\1\35\13\0"+
    "\43\35\3\0\1\35\14\0\60\35\16\0\4\35\13\0"+
    "\12\57\1\35\1\0\1\35\43\0\22\35\1\0\31\35"+
    "\124\0\7\35\1\0\1\35\1\0\4\35\1\0\17\35"+
    "\1\0\12\35\7\0\57\35\21\0\12\57\13\0\10\35"+
    "\2\0\2\35\2\0\26\35\1\0\7\35\1\0\2\35"+
    "\1\0\5\35\3\0\1\35\22\0\1\35\14\0\5\35"+
    "\236\0\65\35\22\0\4\35\5\0\12\57\5\0\1\35"+
    "\40\0\60\35\24\0\2\35\1\0\1\35\10\0\12\57"+
    "\246\0\57\35\51\0\4\35\44\0\60\35\24\0\1\35"+
    "\13\0\12\57\46\0\53\35\15\0\1\35\7\0\12\57"+
    "\66\0\33\35\25\0\12\57\306\0\54\35\164\0\40\31"+
    "\40\37\12\57\25\0\1\35\240\0\10\35\2\0\47\35"+
    "\20\0\1\35\1\0\1\35\34\0\1\35\12\0\50\35"+
    "\7\0\1\35\25\0\1\35\13\0\56\35\23\0\1\35"+
    "\42\0\71\35\7\0\11\35\1\0\45\35\21\0\1\35"+
    "\17\0\12\57\30\0\36\35\160\0\7\35\1\0\2\35"+
    "\1\0\46\35\25\0\1\35\11\0\12\57\6\0\6\35"+
    "\1\0\2\35\1\0\40\35\16\0\1\35\7\0\12\57"+
    "\u0136\0\23\35\15\0\232\35\346\0\304\35\274\0\57\35"+
    "\321\0\107\35\271\0\71\35\7\0\37\35\1\0\12\57"+
    "\146\0\36\35\22\0\60\35\20\0\4\35\14\0\12\57"+
    "\11\0\25\35\5\0\23\35\260\0\40\31\40\37\200\0"+
    "\113\35\5\0\1\35\102\0\15\35\100\0\2\35\1\0"+
    "\1\35\34\0\370\35\10\0\363\35\15\0\37\35\61\0"+
    "\3\35\21\0\4\35\10\0\u018c\35\4\0\153\35\5\0"+
    "\15\35\3\0\11\35\7\0\12\35\146\0\32\31\32\37"+
    "\32\31\7\37\1\0\22\37\32\31\32\37\1\31\1\0"+
    "\2\31\2\0\1\31\2\0\2\31\2\0\4\31\1\0"+
    "\10\31\4\37\1\0\1\37\1\0\7\37\1\0\13\37"+
    "\32\31\32\37\2\31\1\0\4\31\2\0\10\31\1\0"+
    "\7\31\1\0\32\37\2\31\1\0\4\31\1\0\5\31"+
    "\1\0\1\31\3\0\7\31\1\0\32\37\32\31\32\37"+
    "\32\31\32\37\32\31\32\37\32\31\32\37\32\31\32\37"+
    "\32\31\34\37\2\0\31\31\1\0\31\37\1\0\6\37"+
    "\31\31\1\0\31\37\1\0\6\37\31\31\1\0\31\37"+
    "\1\0\6\37\31\31\1\0\31\37\1\0\6\37\31\31"+
    "\1\0\31\37\1\0\6\37\1\31\1\37\2\0\62\57"+
    "\55\35\12\0\7\35\2\0\12\57\4\0\1\35\u0171\0"+
    "\54\35\4\0\12\57\6\0\305\35\73\0\42\31\42\37"+
    "\7\0\1\35\4\0\12\57\246\0\4\35\1\0\33\35"+
    "\1\0\2\35\1\0\1\35\2\0\1\35\1\0\12\35"+
    "\1\0\4\35\1\0\1\35\1\0\1\35\6\0\1\35"+
    "\4\0\1\35\1\0\1\35\1\0\1\35\1\0\3\35"+
    "\1\0\2\35\1\0\1\35\2\0\1\35\1\0\1\35"+
    "\1\0\1\35\1\0\1\35\1\0\1\35\1\0\2\35"+
    "\1\0\1\35\2\0\4\35\1\0\7\35\1\0\4\35"+
    "\1\0\4\35\1\0\1\35\1\0\12\35\1\0\21\35"+
    "\5\0\3\35\1\0\5\35\1\0\21\35\164\0\32\60"+
    "\6\0\32\60\6\0\32\60\166\0\327\35\51\0\65\35"+
    "\13\0\336\35\2\0\u0182\35\16\0\u0131\35\37\0\36\35"+
    "\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28928];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\2\1\4\2\2"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\11\26\1\27\1\30\1\1\1\2\1\0\1\31"+
    "\1\0\1\32\1\0\1\33\3\0\1\34\1\35\1\36"+
    "\3\26\1\37\6\26\1\40\1\41\1\32\2\42\12\26"+
    "\1\43\2\26\1\44\2\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\142\0\223\0\304\0\365\0\142"+
    "\0\u0126\0\u0157\0\142\0\142\0\142\0\142\0\142\0\u0188"+
    "\0\142\0\142\0\u01b9\0\u01ea\0\142\0\142\0\u021b\0\142"+
    "\0\u024c\0\142\0\142\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341"+
    "\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\142\0\u0467\0\u0498"+
    "\0\u04c9\0\142\0\365\0\142\0\u04fa\0\142\0\u052b\0\u055c"+
    "\0\u058d\0\u05be\0\142\0\142\0\u05ef\0\u0620\0\u0651\0\u027d"+
    "\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777\0\142\0\142"+
    "\0\365\0\142\0\u052b\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c"+
    "\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u027d\0\u0992\0\u09c3"+
    "\0\u027d\0\u09f4\0\u0a25";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\3\1\33\1\3\2\34\1\35\1\36"+
    "\1\37\1\40\1\34\1\41\1\42\1\43\1\34\1\44"+
    "\2\34\1\45\1\46\1\34\1\23\1\31\20\47\1\50"+
    "\34\47\1\3\3\47\63\0\1\51\105\0\1\52\31\0"+
    "\7\53\1\54\23\53\1\55\25\53\11\0\1\56\47\0"+
    "\2\57\4\0\25\57\1\60\25\57\20\0\1\61\61\0"+
    "\1\62\1\0\1\23\33\0\1\23\25\0\1\63\63\0"+
    "\1\64\54\0\1\31\5\0\1\31\3\0\17\31\3\0"+
    "\1\31\24\0\1\34\5\0\1\34\3\0\17\34\3\0"+
    "\1\34\24\0\1\34\5\0\1\34\3\0\1\34\1\65"+
    "\15\34\3\0\1\34\24\0\1\34\5\0\1\34\3\0"+
    "\7\34\1\66\7\34\3\0\1\34\24\0\1\34\5\0"+
    "\1\34\3\0\1\34\1\67\15\34\3\0\1\34\24\0"+
    "\1\34\5\0\1\34\3\0\5\34\1\70\6\34\1\71"+
    "\2\34\3\0\1\34\24\0\1\34\5\0\1\34\3\0"+
    "\4\34\1\72\10\34\1\73\1\34\3\0\1\34\24\0"+
    "\1\34\5\0\1\34\3\0\12\34\1\74\4\34\3\0"+
    "\1\34\24\0\1\34\5\0\1\34\3\0\4\34\1\75"+
    "\12\34\3\0\1\34\24\0\1\34\5\0\1\34\3\0"+
    "\12\34\1\76\4\34\3\0\1\34\21\0\1\77\40\0"+
    "\20\47\1\0\34\47\1\0\3\47\55\0\1\100\30\0"+
    "\1\4\33\0\7\53\1\101\23\53\1\55\25\53\12\0"+
    "\1\102\46\0\2\57\4\0\4\57\1\103\46\57\2\61"+
    "\1\4\2\0\1\5\53\61\23\0\1\62\60\0\1\34"+
    "\5\0\1\34\3\0\14\34\1\104\2\34\3\0\1\34"+
    "\24\0\1\34\5\0\1\34\3\0\13\34\1\105\3\34"+
    "\3\0\1\34\24\0\1\34\5\0\1\34\3\0\7\34"+
    "\1\106\7\34\3\0\1\34\24\0\1\34\5\0\1\34"+
    "\3\0\4\34\1\107\12\34\3\0\1\34\24\0\1\34"+
    "\5\0\1\34\3\0\16\34\1\70\3\0\1\34\24\0"+
    "\1\34\5\0\1\34\3\0\7\34\1\110\7\34\3\0"+
    "\1\34\24\0\1\34\5\0\1\34\3\0\6\34\1\111"+
    "\10\34\3\0\1\34\24\0\1\34\5\0\1\34\3\0"+
    "\1\34\1\112\12\34\1\113\2\34\3\0\1\34\24\0"+
    "\1\34\5\0\1\34\3\0\15\34\1\114\1\34\3\0"+
    "\1\34\24\0\1\34\5\0\1\34\3\0\1\34\1\70"+
    "\15\34\3\0\1\34\24\0\1\34\5\0\1\34\3\0"+
    "\4\34\1\70\12\34\3\0\1\34\24\0\1\34\5\0"+
    "\1\34\3\0\13\34\1\114\3\34\3\0\1\34\24\0"+
    "\1\34\5\0\1\34\3\0\12\34\1\115\4\34\3\0"+
    "\1\34\24\0\1\34\5\0\1\34\3\0\7\34\1\116"+
    "\7\34\3\0\1\34\24\0\1\34\5\0\1\34\3\0"+
    "\10\34\1\117\6\34\3\0\1\34\24\0\1\34\5\0"+
    "\1\34\3\0\3\34\1\70\13\34\3\0\1\34\24\0"+
    "\1\34\5\0\1\34\3\0\15\34\1\120\1\34\3\0"+
    "\1\34\24\0\1\34\5\0\1\34\3\0\4\34\1\121"+
    "\12\34\3\0\1\34\24\0\1\34\5\0\1\34\3\0"+
    "\1\34\1\122\15\34\3\0\1\34\24\0\1\34\5\0"+
    "\1\34\3\0\14\34\1\70\2\34\3\0\1\34\24\0"+
    "\1\34\5\0\1\34\3\0\12\34\1\123\4\34\3\0"+
    "\1\34\24\0\1\34\5\0\1\34\3\0\14\34\1\105"+
    "\2\34\3\0\1\34\24\0\1\34\5\0\1\34\3\0"+
    "\10\34\1\70\6\34\3\0\1\34\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2646];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\2\11\3\1\1\11\2\1\5\11\1\1"+
    "\2\11\2\1\2\11\1\1\1\11\1\1\2\11\12\1"+
    "\1\11\2\1\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\3\0\1\1\2\11\12\1\2\11\1\1\1\11\21\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private int ntk;

    public int readTokensCount() {
        return ntk;
    }

    private Token symbol(TOKEN_TYPE t) {
        ntk++;
        return new Token(t, yytext(), yyline + 1, yycolumn + 1);
    }

    private Token symbol(TOKEN_TYPE t, String lex, Object value) {
        ntk++;
        return new Token(t, lex, value, yyline + 1, yycolumn + 1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexTest(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
          // fall through
          case 37: break;
          case 2:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
          // fall through
          case 38: break;
          case 3:
            { return symbol(TOKEN_TYPE.LOGICAL_NOT);
            }
          // fall through
          case 39: break;
          case 4:
            { return symbol(TOKEN_TYPE.MOD);
            }
          // fall through
          case 40: break;
          case 5:
            { return symbol(TOKEN_TYPE.LPAREN);
            }
          // fall through
          case 41: break;
          case 6:
            { return symbol(TOKEN_TYPE.RPAREN);
            }
          // fall through
          case 42: break;
          case 7:
            { return symbol(TOKEN_TYPE.MULT);
            }
          // fall through
          case 43: break;
          case 8:
            { return symbol(TOKEN_TYPE.PLUS);
            }
          // fall through
          case 44: break;
          case 9:
            { return symbol(TOKEN_TYPE.COMMA);
            }
          // fall through
          case 45: break;
          case 10:
            { return symbol(TOKEN_TYPE.MINUS);
            }
          // fall through
          case 46: break;
          case 11:
            { return symbol(TOKEN_TYPE.PERIOD);
            }
          // fall through
          case 47: break;
          case 12:
            { return symbol(TOKEN_TYPE.DIV);
            }
          // fall through
          case 48: break;
          case 13:
            { return symbol(TOKEN_TYPE.INTEGER, yytext(), Integer.parseInt(yytext()));
            }
          // fall through
          case 49: break;
          case 14:
            { return symbol(TOKEN_TYPE.COLON);
            }
          // fall through
          case 50: break;
          case 15:
            { return symbol(TOKEN_TYPE.SEMI);
            }
          // fall through
          case 51: break;
          case 16:
            { return symbol(TOKEN_TYPE.LESS_THAN);
            }
          // fall through
          case 52: break;
          case 17:
            { return symbol(TOKEN_TYPE.ASSIGN);
            }
          // fall through
          case 53: break;
          case 18:
            { return symbol(TOKEN_TYPE.GREATER_THAN);
            }
          // fall through
          case 54: break;
          case 19:
            { return symbol(TOKEN_TYPE.TYPE_NAME, yytext(), yytext());
            }
          // fall through
          case 55: break;
          case 20:
            { return symbol(TOKEN_TYPE.LBRACKET);
            }
          // fall through
          case 56: break;
          case 21:
            { return symbol(TOKEN_TYPE.RBRACKET);
            }
          // fall through
          case 57: break;
          case 22:
            { return symbol(TOKEN_TYPE.ID);
            }
          // fall through
          case 58: break;
          case 23:
            { return symbol(TOKEN_TYPE.LBRACE);
            }
          // fall through
          case 59: break;
          case 24:
            { return symbol(TOKEN_TYPE.RBRACE);
            }
          // fall through
          case 60: break;
          case 25:
            { return symbol(TOKEN_TYPE.NOT_EQUAL_TO);
            }
          // fall through
          case 61: break;
          case 26:
            { return symbol(TOKEN_TYPE.STRING, yytext(), (yytext()));
            }
          // fall through
          case 62: break;
          case 27:
            { return symbol(TOKEN_TYPE.LOGICAL_AND);
            }
          // fall through
          case 63: break;
          case 28:
            { return symbol(TOKEN_TYPE.FLOAT, yytext(), Float.parseFloat(yytext()));
            }
          // fall through
          case 64: break;
          case 29:
            { return symbol(TOKEN_TYPE.SCOPE_RESOLUTION);
            }
          // fall through
          case 65: break;
          case 30:
            { return symbol(TOKEN_TYPE.EQUAL_TO);
            }
          // fall through
          case 66: break;
          case 31:
            { return symbol(TOKEN_TYPE.KEYWORD, yytext(), yytext());
            }
          // fall through
          case 67: break;
          case 32:
            { yybegin(COMMENT);
            }
          // fall through
          case 68: break;
          case 33:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 69: break;
          case 34:
            { return symbol(TOKEN_TYPE.CHAR, yytext(), (yytext()));
            }
          // fall through
          case 70: break;
          case 35:
            { return symbol(TOKEN_TYPE.NULL, yytext(), yytext());
            }
          // fall through
          case 71: break;
          case 36:
            { return symbol(TOKEN_TYPE.BOOLEAN, yytext(), yytext());
            }
          // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
